"""FastAPI deployment of the AI Customer Support Chatbot.

Run it:
    uvicorn api:app --reload

Call it:
    curl -X POST http://127.0.0.1:8000/chat \
         -H 'content-type: application/json' \
         -d '{"message": "How long is the warranty?", "session_id": "user-1"}'

Interactive docs (auto-generated by FastAPI): http://127.0.0.1:8000/docs

Why FastAPI as well as Streamlit? Streamlit is great for a demo UI, but real
products expose the bot as an HTTP API that a website, mobile app, or another
service can call. `session_id` maps to the agent's memory thread, so each caller
keeps its own conversation.
"""

from fastapi import FastAPI
from pydantic import BaseModel

from src import config
from src.support import SupportChatbot

app = FastAPI(title=f"{config.COMPANY} Support Chatbot")

# Build the bot once at startup and reuse it (memory is partitioned per session_id).
bot = SupportChatbot()


class ChatRequest(BaseModel):
    message: str
    session_id: str = "default"


class ChatResponse(BaseModel):
    answer: str
    session_id: str


@app.get("/health")
def health():
    """Liveness probe (useful for cloud deployments / load balancers)."""
    return {"status": "ok", "company": config.COMPANY}


@app.post("/chat", response_model=ChatResponse)
def chat(req: ChatRequest):
    """Send a customer message; get the bot's answer back. Memory keyed by session_id."""
    answer = bot.ask(req.message, session_id=req.session_id)
    return ChatResponse(answer=answer, session_id=req.session_id)
